apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - full-access-group
      rolearn: arn:aws:iam::729371877866:role/github-actions-role
      username: github-actions-role
   